name = "slog-user"

[pages]
compatibility_date = "2026-01-30"

[pages.build]
output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "slog-user"
database_id = "f79ab3ea-cc9a-4f40-86d7-635e960b28a0"